### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by MoonlightFeathers** [yoterel/iCatcher#14]
Hello! Sorry to bother you, but I'm relatively a newbie with python / anaconda and I am trying to figure this issue I got stuck at a bit. 

I got to Step 4 and am attempting to run iCatcher with a video file but regularly get the "NotImplementedError" raised.

> (newenv) C:\Users\riku1>python icatcher.py --source_type file C:\Users\riku1\OneDrive\Pictures\CameraRoll\video.mp4 --show_output
2021-11-11 15:11:07.738874: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-11-11 15:11:07.749012: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: LAPTOP-02RGMM16
2021-11-11 15:11:07.749318: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: LAPTOP-02RGMM16
INFO:root:using the following values for per-channel mean: [0.41304266, 0.34594961, 0.27693587]
INFO:root:using the following values for per-channel std: [0.28606387, 0.2466201, 0.20393684]
2021-11-11 15:11:08.562646: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\riku1\icatcher.py", line 77, in <module>
    predict.predict_from_video(args)
  File "C:\Users\riku1\predict.py", line 75, in predict_from_video
    raise NotImplementedError
NotImplementedError

And line 75 in predict.py looks similar to this

>def predict_from_video(opt):
    # initialize
    logging.info("using the following values for per-channel mean: {}".format(opt.per_channel_mean))
    logging.info("using the following values for per-channel std: {}".format(opt.per_channel_std))
    face_model_file = Path("models", "face_model.caffemodel")
    config_file = Path("models", "config.prototxt")
    if opt.model == "icatcher":
        path_to_primary_model = Path("models", "model.h5")
        import tensorflow as tf
        primary_model = tf.keras.models.load_model(str(path_to_primary_model))
        resize_window = 75
    elif opt.model == "icatcher+":
        path_to_primary_model = Path("models", "icatcher+.pt")
        import torch
        primary_model = GazeCodingModel(device=opt.gpu_id, n=5, add_box=True).to(opt.gpu_id)
        if opt.gpu_id == 'cpu':
            primary_model.load_state_dict(torch.load(str(path_to_primary_model), map_location=torch.device('cpu')))
        else:
            primary_model.load_state_dict(torch.load(str(path_to_primary_model)))
        primary_model.eval()
        resize_window = 100
    else:
        raise NotImplementedError
    classes = {'away': 0, 'left': 1, 'right': 2}
    reverse_dict = {0: 'away', 1: 'left', 2: 'right'}
    sequence_length = 9
    loc = -5
    # load face extractor model
    face_model = cv2.dnn.readNetFromCaffe(str(config_file), str(face_model_file))
    # set video source
    if opt.source_type == 'file':
        video_path = Path(opt.source)
        if video_path.is_dir():
            logging.warning("Video folder provided as source. Make sure it contains video files only.")
            video_paths = list(video_path.glob("*"))
            video_paths = [str(x) for x in video_paths]
        elif video_path.is_file():
            video_paths = [str(video_path)]
        else:
            raise NotImplementedError

If anyone has any tips on how to solve this it would be really appreciated since I am a bit lost on how to navigate / get around the NotImplementedError and am not having much luck finding it online

**Comment by yoterel** [comment]
Seems like the path you are passing does not exist (as source)
Can you paste the command line you are running?

**Comment by MoonlightFeathers** [comment]
Of course! I'm runing this, with "newenv" as the environment name I used in step 2 instead of "env"

"C:\Users\riku1\OneDrive\Pictures\CameraRoll\video.mp4" is the path file to the video

(newenv) C:\Users\riku1>python icatcher.py --source_type file C:\Users\riku1\OneDrive\Pictures\CameraRoll\video.mp4 --show_output

**Comment by yoterel** [comment]
Can you try replacing the path provided with forward slashes ("/") ? 
Another thing to try is wrapping the path provided with quotation marks like so:
`python icatcher.py --source_type file "C:\Users\riku1\OneDrive\Pictures\CameraRoll\video.mp4" --show_output`
Also, please make absolutely sure this path is correct (copy it, paste it in an explorer and see if the file opens).

**Comment by MoonlightFeathers** [comment]
Oh I changed where the file was (since it didn't work when I pasted it into an explorer) and opened it up in a new folder in my documents and it seems to have worked! Thanks, I'll have to see if this also works on the computer I actually need to run this on but I'll let you know if it is still an issue. Thank you so much!
