### ISSUE TITLE
Model Loading Error

### ISSUE THREAD

**Issue by cindy-chiang** [yoterel/iCatcher#16]
Hi, I'm having some trouble with running iCatcher. I am running into a loading error for the models, and I'm a bit stuck on how to resolve the issue. Just for some context, I using on a Mac OS and running on Python 3.8.12.  The command line I'm using has been pasted below and the output I get is pasted below that chunk. 

`python /Users/cindyc/Documents/GitHub/iCatcher/icatcher.py   --source_type file /Users/cindyc/Documents/GitHub/iCatcher/sample.mp4 --output_annotation /Users/cindyc/Documents/GitHub/iCatcher/annot`

`(iCatcher) MacBook-Pro:~ cindyc$ python /Users/cindyc/Documents/GitHub/iCatcher/icatcher.py   --source_type file /Users/cindyc/Documents/GitHub/iCatcher/sample.mp4 --output_annotation /Users/cindyc/Documents/GitHub/iCatcher/annot
INFO:root:using the following values for per-channel mean: [0.41304266, 0.34594961, 0.27693587]
INFO:root:using the following values for per-channel std: [0.28606387, 0.2466201, 0.20393684]
Traceback (most recent call last):
  File "/Users/cindyc/Documents/GitHub/iCatcher/icatcher.py", line 81, in <module>
    predict.predict_from_video(args)
  File "/Users/cindyc/Documents/GitHub/iCatcher/predict.py", line 45, in predict_from_video
    primary_model = tf.keras.models.load_model(str(path_to_primary_model))
  File "/Users/cindyc/anaconda2/envs/iCatcher/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/cindyc/anaconda2/envs/iCatcher/lib/python3.8/site-packages/keras/saving/save.py", line 209, in load_model
    raise IOError(f'No file or directory found at {filepath}')
OSError: No file or directory found at models/model.h5
`

Thank you so much for any help and for putting iCatcher together!

**Comment by yoterel** [comment]
I'm assuming the models were downloaded to the folder models?
if so, can you try running the same command but when you are already inside /Users/cindyc/Documents/GitHub/iCatcher?
i.e. do:
`cd /Users/cindyc/Documents/GitHub/iCatcher/ `
and then:
`python icatcher.py --source_type file sample.mp4 --output_annotation annot`

**Comment by cindy-chiang** [comment]
Thanks so much for the help! Running the command inside solved the problem!
