### ISSUE TITLE
Cannot run the example line 

### ISSUE THREAD

**Issue by tianchu-shu** [yoterel/iCatcher#17]
Hi I tried to use the exmaple.mp4 to run the icatcher.py
But no matter I use file or webcam or 'file' or 'webcam', I kept getting error message as below. Can you help?Thanks.
icatcher.py: error: unrecognized arguments: --'webcam' --show_out_put

>python icatcher.py --'file' C:\Users\**\Downloads\example.mp4 --show_out_put

**Comment by yoterel** [comment]
1) Replace --'file' C:\Users**\Downloads\example.mp4 with --source_type file C:\Users**\Downloads\example.mp4
2) The command line argument is "--show_output" not "--show_out_put".

all in all your command line should look like this:

`python icatcher.py --source_type file C:\Users**\Downloads\example.mp4 --show_output`

Try fixing those and let me know if it helped.

**Comment by tianchu-shu** [comment]
Thanks.
