### ISSUE TITLE
Can the show_output output be provided?

### ISSUE THREAD

**Issue by tianchu-shu** [yoterel/iCatcher#19]
Hi, 
I was using your code on my video, and I noticed when I run show_output, I have the classifications by every frame. For my video (99 seconds, 12 frames/sec), I have about 1186 lines of classfications which is by every frame. First 3 lines are pasted below:
INFO:root:frame: 0, class: away
INFO:root:frame: 1, class: right
INFO:root:frame: 2, class: away
INFO:root:frame: 3, class: right

But when I run the output_annotation line, the output is a lot less (which is by timestamp), first 3 lines are pasted below:
666,0,away
750,0,right
833,0,away
I was wondering is it possible for me to just get an output like the show_output format? Thanks a lot!

**Comment by yoterel** [comment]
You can pass the "--output_format raw_output" flag:
`--output_format raw_output`

See icatcher.py --help for more information
