### ISSUE TITLE
iCatcher Speeding up Output Videos

### ISSUE THREAD

**Issue by nereeth** [yoterel/iCatcher#20]
For some of the videos that I run through iCatcher, iCatcher automatically speeds up the output videos by a significant amount (ex. I input a video that is 2 minutes long, iCatcher returns a video that is 200 miliseconds long). Clipping videos to make them shorter solves the problem for some, but not all videos. Not sure what is causing this problem or if there is a setting I can change to prevent it.

Using:
- iCatcher version 0.0.10
- Python version 3.10.09
- Windows operating sytem

**Comment by yoterel** [comment]
Hi,
I believe you have mistakenly posted this issue in the wrong repo (this repo is the old icatcher)
please reopen in icatcher_plus [here ](https://github.com/icatcherplus/icatcher_plus)
