### ISSUE TITLE
cv2.error Mac

### ISSUE THREAD

**Issue by prernaaneja** [yoterel/iCatcher#5]
Hi, 

I have been getting the following error- 

Traceback (most recent call last):
  File "example.py", line 205, in <module>
    predict(opt)
  File "example.py", line 53, in predict
    face_model = cv2.dnn.readNetFromCaffe(str(config_file), str(face_model_file))
cv2.error: OpenCV(4.1.2) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "config.prototxt" in function 'ReadProtoFromTextFile'

I am working on macOS using Anaconda. Could you please help me with this?

**Comment by yoterel** [comment]
Have you downloaded the config.prototxt file as per README instructions?

**Comment by prernaaneja** [comment]
yes, I have config.prototxt, face_model.caffemodel and model.h5 in the same folder as example.py

**Comment by yoterel** [comment]
Can you show the parameters you run the script with?

**Comment by prernaaneja** [comment]
python example.py --source_type file ./example.mp4 --use_tensorflow_2

**Comment by yoterel** [comment]
Do those files have read permission?  (config.prototxt)
Are you running the interpreter from the folder that example.py is in? try replacing the "config_file = Path("config.prototxt")" in the code to an absolute path of where config.prototxt is at, tell me if this solves the problem

**Comment by prernaaneja** [comment]
yep, changing the path helped. I have the output .csv and mp4 file. although its empty. I think that's an error from my side. 

 Error message-

"using the following values for per-channel mean: [0.41304266, 0.34594961, 0.27693587]
using the following values for per-channel std: [0.41304266, 0.34594961, 0.27693587]
2020-11-18 13:39:15.288245: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-18 13:39:15.288438: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
predicting on file: example.mp4
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6"

I'll try to fix this and re-run it. Thank you!
